version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/modoco-backend
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
