version: 1.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/modoco-backend
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
