export const API_DOC_TYPE = {
  CREATE_USER: 'CREATE_USER',
  FIND_ALL_USERS: 'FIND_ALL_USERS',
  GET_ME: 'GET_ME',
  FIND_USER_BY_UID: 'FIND_USER_BY_UID',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER_BY_UID: 'DELETE_USER_BY_UID',
} as const;

export type API_DOC_TYPE = typeof API_DOC_TYPE[keyof typeof API_DOC_TYPE];
