export const API_DOC_TYPE = {
  ADD_FRIEND: 'ADD_FRIEND',
  GET_FRIENDSHIPS: 'GET_FRIENDSHIPS',
  ACCEPT_FRIENDSHIP: 'ACCEPT_FRIENDSHIP',
  DELETE_FRIENDSHIP: 'DELETE_FRIENDSHIP',
} as const;

export type API_DOC_TYPE = typeof API_DOC_TYPE[keyof typeof API_DOC_TYPE];
